### 5. Write a Python program to generate a random number?

#For generate random number in python we need to import one utility which is Random.

import random

#For printing any random number we just use random and only generate flote value
ran_val_flote=random.random()
print("The random float value is generated by random is ",ran_val_flote)

#For printing any intiger random number we just use randint and only generate integer value inbetween 1 to 1000
ran_val_int=random.randint(1, 1000)
print("The random integer value is generated by randint inbetween 1 to 1000 is ",ran_val_int)

#Output 
#The random float value is generated by random is  0.2101719873642489
#The random integer value is generated by randint inbetween 1 to 1000 is  817